var CONFIG={SPREADSHEET_ID:'18mVJgfMaPjs8ppmlhf5JVYvHhysHYy9L77bwfRPI5O0',WO_SPREADSHEET_ID:'15T21iCLPb8vwzFNtUbWjZ_T3RGGDZ-Y9UX5-4UV1Zgk',TEMUAN_SPREADSHEET_ID:'1qFBQq3hMTA98ZV6UWg-Pj5sz-J41pm0r13TLYP2LF0I',USERS_SHEET:'User_App_Mobile',WO_INSJAR_SHEET:'WO_Ins_Jar',TEMUAN_SHEET:'Inp_Temuan',SESSION_TTL_SEC:900,MASTER_SHEETS:['User_App_Mobile','Master_Penyulang','Master_Keypoint','List_Temuan','Jenis Pohon']};
var USER_COL={no:0,kodeUiw:1,kodeUp3:2,kodeUlp:3,ulp:4,username:5,password:6,role:7,bidang:8,tim:9,subTim:10,aksesMenu:11};
function doGet(e){var p=(e&&e.parameter)||{},a=String(p.action||'health').trim();try{if(a==='health')return json_({success:true,service:'SiManDist API',version:'2.4.0'});if(a==='loginPerangkat')return json_(loginPerangkat_(p.username,p.password,p.perangkat));if(a==='cekPerangkat')return json_(cekPerangkat_(p.deviceToken));if(a==='logoutPerangkat')return json_(logoutPerangkat_(p.deviceToken,p.token));if(a==='cekSesi')return json_(cekSesi_(p.token));if(a==='logout')return json_(logout_(p.token));if(a==='getMasterData')return json_(getMasterData_(p.token));if(a==='getWoInsjar')return json_(getWoInsjar_(p.token));if(a==='getTemuanInspeksi')return json_(getTemuanInspeksi_(p.token,p.kodeWo));return json_({success:false,message:'Action API tidak dikenal: '+a});}catch(x){return json_({success:false,message:'Error server: '+x.message});}}
function doPost(e){try{var b=parseBody_(e),a=String(b.action||'').trim();if(a==='login'||a==='loginPerangkat')return json_(loginPerangkat_(b.username,b.password,b.perangkat));if(a==='cekPerangkat')return json_(cekPerangkat_(b.deviceToken));if(a==='logoutPerangkat')return json_(logoutPerangkat_(b.deviceToken,b.token));if(a==='cekSesi')return json_(cekSesi_(b.token));if(a==='logout')return json_(logout_(b.token));if(a==='getMasterData')return json_(getMasterData_(b.token));if(a==='getWoInsjar')return json_(getWoInsjar_(b.token));if(a==='syncWoInsjar')return json_(syncWoInsjar_(b.token,b.rows));if(a==='syncTemuanInspeksi')return json_(syncTemuanInspeksi_(b.token,b.row));return json_({success:false,message:'Action API tidak dikenal: '+a});}catch(x){return json_({success:false,message:'Error server: '+x.message});}}
function loginPerangkat_(u,p,d){u=String(u||'').trim();p=String(p||'');if(!u||!p)return{success:false,message:'Username dan kata sandi wajib diisi.'};var r=findUser_(u);if(!r||String(r[USER_COL.password]||'')!==p)return{success:false,message:'Username atau kata sandi salah.'};var dt=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,''),now=Date.now();PropertiesService.getScriptProperties().setProperty('device_'+dt,JSON.stringify({username:String(r[USER_COL.username]).trim(),passwordSignature:sha256_(p),createdAt:now,lastUsedAt:now,device:String(d||'').substring(0,100)}));var s=issueSession_(r,dt);s.success=true;s.deviceToken=dt;return s;}
function cekPerangkat_(t){t=String(t||'').trim();if(!t)return{success:false,kode:'TANPA_TOKEN',message:'Belum ada sesi perangkat.'};var p=PropertiesService.getScriptProperties(),raw=p.getProperty('device_'+t);if(!raw)return{success:false,kode:'PERANGKAT_TIDAK_DIKENAL',message:'Sesi perangkat tidak dikenali. Silakan login ulang.'};var rec=JSON.parse(raw),r=findUser_(rec.username);if(!r){p.deleteProperty('device_'+t);return{success:false,kode:'AKUN_TIDAK_ADA',message:'Akun sudah tidak terdaftar.'};}if(sha256_(String(r[USER_COL.password]||''))!==String(rec.passwordSignature||'')){p.deleteProperty('device_'+t);return{success:false,kode:'PASSWORD_BERUBAH',message:'Password berubah. Silakan login ulang.'};}rec.lastUsedAt=Date.now();p.setProperty('device_'+t,JSON.stringify(rec));var s=issueSession_(r,t);s.success=true;s.deviceToken=t;return s;}
function logoutPerangkat_(d,t){var p=PropertiesService.getScriptProperties();if(d)p.deleteProperty('device_'+String(d).trim());if(t)CacheService.getScriptCache().remove('session_'+String(t).trim());return{success:true};}
function issueSession_(r,d){var t=Utilities.getUuid(),s=userFromRow_(r);s.token=t;s.deviceToken=d;s.loginAt=new Date().toISOString();CacheService.getScriptCache().put('session_'+t,JSON.stringify(s),CONFIG.SESSION_TTL_SEC);return s;}
function cekSesi_(t){var raw=t?CacheService.getScriptCache().get('session_'+String(t)):null;if(!raw)return{success:false,message:'Sesi tidak valid atau sudah berakhir.'};CacheService.getScriptCache().put('session_'+t,raw,CONFIG.SESSION_TTL_SEC);return{success:true,sesi:JSON.parse(raw)};}
function logout_(t){if(t)CacheService.getScriptCache().remove('session_'+String(t));return{success:true};}
function getMasterData_(t){var a=cekSesi_(t);if(a.success!==true)return a;var u=normalize_(a.sesi.username),ss=getSpreadsheet_(),sets={},total=0;for(var i=0;i<CONFIG.MASTER_SHEETS.length;i++){var n=CONFIG.MASTER_SHEETS[i],sh=ss.getSheetByName(n);if(!sh)return{success:false,message:'Sheet tidak ditemukan: '+n};var v=sh.getDataRange().getDisplayValues();if(!v.length){sets[n]=[];continue;}var h=v[0].map(function(x){return String(x).trim();}),rows=[];for(var r=1;r<v.length;r++){if(n===CONFIG.USERS_SHEET&&normalize_(v[r][USER_COL.username])!==u)continue;var item={},has=false;for(var c=0;c<h.length;c++){var k=h[c]||('kolom_'+(c+1));if(n===CONFIG.USERS_SHEET&&normalize_(k)==='password')continue;item[k]=v[r][c];if(v[r][c]!=='')has=true;}if(has)rows.push(item);}sets[n]=rows;total+=rows.length;}return{success:true,generatedAt:new Date().toISOString(),total:total,datasets:sets};}
function woSheet_(){var s=SpreadsheetApp.openById(CONFIG.WO_SPREADSHEET_ID).getSheetByName(CONFIG.WO_INSJAR_SHEET);if(!s)throw new Error('Sheet tidak ditemukan: '+CONFIG.WO_INSJAR_SHEET);return s;}
function getWoInsjar_(t){var a=cekSesi_(t);if(a.success!==true)return a;var s=woSheet_(),v=s.getDataRange().getDisplayValues();if(v.length<2)return{success:true,total:0,totalSheet:0,rows:[]};var h=v[0].map(function(x){return String(x).trim();}),ix={};for(var i=0;i<h.length;i++)ix[normalize_(h[i])]=i;var kw=ix['kode wo'],ku=ix['kode ulp'],ul=ix['ulp'];if(kw===undefined)return{success:false,message:'Header Kode WO tidak ditemukan.'};var userK=normalizeCode_(a.sesi.kodeUlp),userU=normalize_(a.sesi.ulp),rows=[],valid=0;for(var r=1;r<v.length;r++){var kode=String(v[r][kw]||'').trim();if(!kode)continue;valid++;var rk=ku===undefined?'':normalizeCode_(v[r][ku]),ru=ul===undefined?'':normalize_(v[r][ul]),from=normalizeCode_(kode.replace(/^INSJAR-/i,'').substring(0,userK.length));if((userK||userU)&&!(userK&&(rk===userK||from===userK))&&!(userU&&ru&&(ru===userU||ru.indexOf(userU)>=0||userU.indexOf(ru)>=0)))continue;var item={};for(var c=0;c<h.length;c++)item[h[c]||('kolom_'+(c+1))]=v[r][c];rows.push(item);}return{success:true,total:rows.length,totalSheet:valid,rows:rows};}
function syncWoInsjar_(t,rows){var a=cekSesi_(t);if(a.success!==true)return a;if(!rows||!rows.length)return{success:true,diproses:0};var lock=LockService.getScriptLock();lock.waitLock(20000);try{var s=woSheet_(),v=s.getDataRange().getValues(),h=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0],ix={};for(var i=0;i<h.length;i++)ix[normalize_(h[i])]=i;var ki=ix['kode wo'],map={};for(var r=1;r<v.length;r++){var k=String(v[r][ki]||'').trim();if(k)map[k]=r+1;}var done=0;for(var j=0;j<rows.length;j++){var d=rows[j]||{},kode=String(d['Kode WO']||'').trim();if(!kode)continue,target=h.map(function(x){return d[x]===undefined||d[x]===null?'':d[x];});if(map[kode]){target[0]=v[map[kode]-1][0];s.getRange(map[kode],1,1,h.length).setValues([target]);}else{target[0]=s.getLastRow();s.appendRow(target);}done++;}return{success:true,diproses:done};}finally{lock.releaseLock();}}
function temuanSheet_(){var s=SpreadsheetApp.openById(CONFIG.TEMUAN_SPREADSHEET_ID).getSheetByName(CONFIG.TEMUAN_SHEET);if(!s)throw new Error('Sheet tidak ditemukan: '+CONFIG.TEMUAN_SHEET);return s;}
function getTemuanInspeksi_(t,kodeWo){var a=cekSesi_(t);if(a.success!==true)return a;var s=temuanSheet_(),v=s.getDataRange().getDisplayValues();if(v.length<2)return{success:true,rows:[]};var h=v[0].map(function(x){return String(x).trim();}),ki=h.map(normalize_).indexOf('kode wo'),rows=[];for(var r=1;r<v.length;r++){if(String(v[r][ki]||'').trim()!==String(kodeWo||'').trim())continue;var x={};for(var c=0;c<h.length;c++)x[h[c]]=v[r][c];rows.push(x);}return{success:true,total:rows.length,rows:rows};}
function syncTemuanInspeksi_(t,row){var a=cekSesi_(t);if(a.success!==true)return a;if(!row)return{success:false,message:'Data temuan kosong.'};var s=temuanSheet_(),h=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0],ki=h.map(normalize_).indexOf('kode temuan'),v=s.getDataRange().getValues(),targetRow=0;for(var r=1;r<v.length;r++)if(String(v[r][ki]||'')===String(row['Kode Temuan']||'')){targetRow=r+1;break;}var folder=folderPath_(String(row['Folder Path']||'')),kode=String(row['Kode Temuan']||''),stamp=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'HHmmss'),link1='',link2='';if(row.fotoTemuanBase64){var f1=folder.createFile(Utilities.newBlob(Utilities.base64Decode(row.fotoTemuanBase64),'image/jpeg',kode+'.Foto Temuan.'+stamp+'.jpg'));link1=f1.getUrl();row['Foto Temuan']=f1.getName();row['Link Foto']=link1;}if(row.fotoLingkunganBase64){var f2=folder.createFile(Utilities.newBlob(Utilities.base64Decode(row.fotoLingkunganBase64),'image/jpeg',kode+'.Foto Lingkungan.'+stamp+'.jpg'));link2=f2.getUrl();row['Foto Lingkungan Sekitaran Tiang']=f2.getName();row['Link Foto Sekitaran Tiang']=link2;}var out=h.map(function(x){return row[x]===undefined||row[x]===null?'':row[x];});if(targetRow){out[0]=v[targetRow-1][0];s.getRange(targetRow,1,1,h.length).setValues([out]);}else{out[0]=s.getLastRow();s.appendRow(out);}return{success:true,linkFoto:link1,linkLingkungan:link2,folderPath:row['Folder Path']};}
function folderPath_(path){var parts=path.split('/').filter(String),f=DriveApp.getRootFolder();for(var i=0;i<parts.length;i++){var it=f.getFoldersByName(parts[i]);f=it.hasNext()?it.next():f.createFolder(parts[i]);}return f;}
function findUser_(u){var r=getUsersRows_(),t=normalize_(u);for(var i=1;i<r.length;i++)if(normalize_(r[i][USER_COL.username])===t)return r[i];return null;}
function userFromRow_(r){return{no:String(r[0]||''),kodeUiw:String(r[1]||''),kodeUp3:String(r[2]||''),kodeUlp:String(r[3]||''),ulp:String(r[4]||''),username:String(r[5]||''),role:String(r[7]||''),bidang:String(r[8]||''),tim:String(r[9]||''),subTim:String(r[10]||''),aksesMenu:String(r[11]||'')};}
function getUsersRows_(){var c=CacheService.getScriptCache(),hit=c.get('users_v2');if(hit)try{return JSON.parse(hit);}catch(_){ }var s=getSpreadsheet_().getSheetByName(CONFIG.USERS_SHEET);if(!s)throw new Error('Sheet user tidak ditemukan.');var r=s.getDataRange().getDisplayValues();try{c.put('users_v2',JSON.stringify(r),300);}catch(_){ }return r;}
function normalize_(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ');}function normalizeCode_(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/^0+/,'');}function getSpreadsheet_(){return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);}function parseBody_(e){return e&&e.postData&&e.postData.contents?JSON.parse(e.postData.contents):{};}function sha256_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8).map(function(b){var x=b<0?b+256:b;return('0'+x.toString(16)).slice(-2);}).join('');}function json_(p){return ContentService.createTextOutput(JSON.stringify(p)).setMimeType(ContentService.MimeType.JSON);}
