import 'dart:convert';
import 'dart:io';
import 'package:sqflite/sqflite.dart';
import '../models/temuan_inspeksi.dart';
import '../models/wo_insjar.dart';
import 'api_service.dart';
import 'sqlite_service.dart';
class TemuanRepository {
 final _db=SqliteService.instance;
 Future<Database> _database()async{final d=await _db.database;await d.execute('''CREATE TABLE IF NOT EXISTS temuan_inspeksi (kode_temuan TEXT PRIMARY KEY,kode_wo TEXT NOT NULL,kode_uiw TEXT DEFAULT '',kode_up3 TEXT DEFAULT '',kode_ulp TEXT DEFAULT '',ulp TEXT DEFAULT '',hari TEXT DEFAULT '',tanggal TEXT DEFAULT '',penyulang TEXT DEFAULT '',section_awal TEXT DEFAULT '',section_akhir TEXT DEFAULT '',section TEXT DEFAULT '',segmen TEXT DEFAULT '',koordinat TEXT DEFAULT '',lat TEXT DEFAULT '',long TEXT DEFAULT '',jenis_object TEXT DEFAULT '',tier TEXT DEFAULT '',temuan TEXT DEFAULT '',jarak REAL,jenis_pohon TEXT DEFAULT '',tinggi_pohon REAL,prioritas TEXT DEFAULT '',foto_temuan TEXT DEFAULT '',foto_lingkungan TEXT DEFAULT '',link_foto TEXT DEFAULT '',link_lingkungan TEXT DEFAULT '',waktu_input TEXT DEFAULT '',user_input TEXT DEFAULT '',folder_path TEXT DEFAULT '',is_dirty INTEGER DEFAULT 1)''');return d;}
 Future<List<TemuanInspeksi>> untukWo(String k)async{final d=await _database();return(await d.query('temuan_inspeksi',where:'kode_wo=?',whereArgs:[k],orderBy:'kode_temuan')).map(TemuanInspeksi.fromMap).toList();}
 Future<String> kodeBaru(String k)async{final d=await _database();final r=await d.rawQuery('SELECT kode_temuan FROM temuan_inspeksi WHERE kode_wo=? ORDER BY kode_temuan DESC LIMIT 1',[k]);var n=0;if(r.isNotEmpty)n=int.tryParse('${r.first['kode_temuan']}'.split('.TO-').last)??0;return '$k.TO-${(n+1).toString().padLeft(3,'0')}';}
 Future<void>simpan(TemuanInspeksi t)async{final d=await _database();await d.insert('temuan_inspeksi',t.toMap(),conflictAlgorithm:ConflictAlgorithm.replace);}
 Future<void>unduh(String token,String k)async{final x=await ApiService.getTemuan(token,k);if(x['success']!=true||x['rows']is! List)return;final d=await _database();for(final r in x['rows'])if(r is Map)await d.insert('temuan_inspeksi',TemuanInspeksi.fromRemote(Map<String,dynamic>.from(r)).toMap(),conflictAlgorithm:ConflictAlgorithm.ignore);}
 Future<void>sinkron(String token)async{final d=await _database();for(final r in await d.query('temuan_inspeksi',where:'is_dirty=1')){final t=TemuanInspeksi.fromMap(r),p=t.toRemote();if(t.fotoTemuan.isNotEmpty&&File(t.fotoTemuan).existsSync())p['fotoTemuanBase64']=base64Encode(await File(t.fotoTemuan).readAsBytes());if(t.fotoLingkungan.isNotEmpty&&File(t.fotoLingkungan).existsSync())p['fotoLingkunganBase64']=base64Encode(await File(t.fotoLingkungan).readAsBytes());final x=await ApiService.syncTemuan(token,p);if(x['success']==true)await d.update('temuan_inspeksi',{'is_dirty':0,'link_foto':'${x['linkFoto']??''}','link_lingkungan':'${x['linkLingkungan']??''}','folder_path':'${x['folderPath']??t.folderPath}'},where:'kode_temuan=?',whereArgs:[t.kodeTemuan]);}}
 Future<List<Map<String,dynamic>>>master(String n)async{final d=await _database();return(await d.query('master_data_rows',columns:['payload_json'],where:'dataset=?',whereArgs:[n])).map((r)=>Map<String,dynamic>.from(jsonDecode('${r['payload_json']}'))).toList();}
 String jenisObject(Map<String,dynamic>s){final v='${s['subTim']??s['tim']??''}'.toLowerCase();if(v.contains('inspeksi jaringan')||v.contains('insjar'))return'Jaringan';if(v.contains('inspeksi gardu')||v.contains('insdu'))return'Gardu';return'';}
 String prioritas(String t,double?j,double?h,List<Map<String,dynamic>>m){if({'Rabas / Pangkas','Tebang Sedang','Tebang Besar'}.contains(t)){final d=j??0,x=h??0;if(x<9)return d>5?'Minor':'Mayor';if(d<3)return'Mayor';if(d<6)return'Sedang';return'Minor';}for(final r in m)if('${r['Temuan']??''}'.trim()==t)return'${r['Prioritas']??''}';return'';}
 static String folder(WoInsjar w,String o,String k,DateTime n){const b=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];return'SiManDist/Rekap Temuan Inspeksi/${w.kodeUlp}/$o/${n.year}/${n.month.toString().padLeft(2,'0')}. ${b[n.month-1]}/${n.day.toString().padLeft(2,'0')}/${w.kodeWo}/$k/';}
}