import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;
import '../models/temuan_inspeksi.dart';
import '../models/wo_insjar.dart';
import '../services/high_accuracy_location_service.dart';
import '../services/temuan_repository.dart';

class TemuanTab extends StatefulWidget{final WoInsjar wo;final Map<String,dynamic>sesi;const TemuanTab({super.key,required this.wo,required this.sesi});@override State<TemuanTab>createState()=>_TemuanTabState();}
class _TemuanTabState extends State<TemuanTab>{
 static const blue=Color(0xFF004D8C),navy=Color(0xFF071B30),amber=Color(0xFFFFB800),muted=Color(0xFF64748B),line=Color(0xFFE2E8F0);
 final repo=TemuanRepository();List<TemuanInspeksi>items=[];bool busy=false;
 @override void initState(){super.initState();_load(remote:true);}
 Future<void>_load({bool remote=false})async{if(remote)await repo.unduh('${widget.sesi['token']??''}',widget.wo.kodeWo);items=await repo.untukWo(widget.wo.kodeWo);if(mounted)setState((){});}
 Future<void>_add()async{final ok=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>TemuanForm(wo:widget.wo,sesi:widget.sesi)));if(ok==true)_load();}
 Future<void>_sync()async{setState(()=>busy=true);try{await repo.sinkron('${widget.sesi['token']??''}');await _load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Temuan berhasil disinkronkan.')));}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext c)=>Stack(children:[ListView(padding:const EdgeInsets.fromLTRB(18,18,18,96),children:[Row(children:[Text('${items.length} Temuan',style:const TextStyle(fontWeight:FontWeight.w800,color:navy,fontSize:16)),const Spacer(),TextButton.icon(onPressed:busy?null:_sync,icon:busy?const SizedBox(width:16,height:16,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.cloud_upload_outlined),label:const Text('Sinkron'))]),if(items.isEmpty)const Padding(padding:EdgeInsets.only(top:48),child:Column(children:[Icon(Icons.fact_check_outlined,size:48,color:blue),SizedBox(height:12),Text('Belum ada temuan',style:TextStyle(fontWeight:FontWeight.w800)),Text('Tambahkan temuan hasil inspeksi.',style:TextStyle(color:muted))]))else ...items.map((t)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(t.kodeTemuan,style:const TextStyle(fontWeight:FontWeight.w800,color:blue))),Text(t.prioritas,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w800))]),const SizedBox(height:8),Text(t.temuan,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800,color:navy)),const SizedBox(height:4),Text('${t.tier} • ${t.segmen}',style:const TextStyle(color:muted,fontSize:12))]))]),Positioned(right:18,bottom:20,child:FloatingActionButton.extended(onPressed:_add,backgroundColor:amber,foregroundColor:navy,icon:const Icon(Icons.add),label:const Text('Temuan',style:TextStyle(fontWeight:FontWeight.w800))))]);
}

class TemuanForm extends StatefulWidget{final WoInsjar wo;final Map<String,dynamic>sesi;const TemuanForm({super.key,required this.wo,required this.sesi});@override State<TemuanForm>createState()=>_TemuanFormState();}
class _TemuanFormState extends State<TemuanForm>{
 static const blue=Color(0xFF004D8C),navy=Color(0xFF071B30),amber=Color(0xFFFFB800),muted=Color(0xFF64748B),line=Color(0xFFE2E8F0);
 final repo=TemuanRepository(),segmen=TextEditingController(),jarak=TextEditingController(),tinggi=TextEditingController();final picker=ImagePicker();
 List<Map<String,dynamic>>listMaster=[],pohonMaster=[];String kode='',object='',tier='',temuan='',pohon='';LocationFix?gps;String foto='',lingkungan='';bool saving=false;
 bool get vegetasi=>{'Rabas / Pangkas','Tebang Sedang','Tebang Besar'}.contains(temuan);
 List<String>get temuanOptions=>listMaster.where((r){final o='${r['Jenis Object']??r['Object']??''}',t='${r['Tier']??''}';return(o.isEmpty||o==object)&&(t.isEmpty||t==tier);}).map((r)=>'${r['Temuan']??''}'.trim()).where((x)=>x.isNotEmpty).toSet().toList();
 @override void initState(){super.initState();_init();}
 Future<void>_init()async{kode=await repo.kodeBaru(widget.wo.kodeWo);object=repo.jenisObject(widget.sesi);listMaster=await repo.master('List_Temuan');pohonMaster=await repo.master('Jenis Pohon');if(mounted)setState((){});}
 @override void dispose(){segmen.dispose();jarak.dispose();tinggi.dispose();super.dispose();}
 Future<void>_gps()async{final f=await HighAccuracyLocationService.acquire(onSample:(_,__){});if(mounted)setState(()=>gps=f);}
 Future<String>_camera(String label)async{final x=await picker.pickImage(source:ImageSource.camera,imageQuality:82,maxWidth:1920);if(x==null)return'';final now=DateTime.now();String two(int v)=>v.toString().padLeft(2,'0');final name='$kode.$label.${two(now.hour)}${two(now.minute)}${two(now.second)}.jpg';final target=p.join(p.dirname(x.path),name);return(await File(x.path).copy(target)).path;}
 String _pick(Map<String,dynamic>r,List<String>keys){for(final k in keys){final v='${r[k]??''}'.trim();if(v.isNotEmpty)return v;}return'';}
 Future<void>_save()async{if(segmen.text.trim().isEmpty||gps==null||object.isEmpty||tier.isEmpty||temuan.isEmpty||foto.isEmpty||lingkungan.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Lengkapi semua data wajib, GPS, dan dua foto.')));return;}if(vegetasi&&(pohon.isEmpty||tinggi.text.isEmpty)){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Jenis dan tinggi pohon wajib diisi.')));return;}setState(()=>saving=true);final now=DateTime.now(),j=double.tryParse(jarak.text.replaceAll(',','.')),h=double.tryParse(tinggi.text.replaceAll(',','.'));final coord=gps!.coordinate.split(',');final pri=repo.prioritas(temuan,j,h,listMaster);final t=TemuanInspeksi(kodeTemuan:kode,kodeWo:widget.wo.kodeWo,kodeUiw:widget.wo.kodeUiw,kodeUp3:widget.wo.kodeUp3,kodeUlp:widget.wo.kodeUlp,ulp:widget.wo.ulp,hari:WoInsjar.hariIndonesia[now.weekday-1],tanggal:WoInsjar.formatTanggal(now),penyulang:widget.wo.penyulang,sectionAwal:widget.wo.sectionAwal,sectionAkhir:widget.wo.sectionAkhir,section:widget.wo.section,segmen:segmen.text.trim(),koordinat:gps!.coordinate,lat:coord.first.trim(),long:coord.length>1?coord[1].trim():'',jenisObject:object,tier:tier,temuan:temuan,jarak:object=='Jaringan'?j:null,jenisPohon:vegetasi?pohon:'',tinggiPohon:vegetasi?h:null,prioritas:pri,fotoTemuan:foto,fotoLingkungan:lingkungan,waktuInput:WoInsjar.stampLengkap(now),userInput:'${widget.sesi['username']??''}',folderPath:TemuanRepository.folder(widget.wo,object,kode,now));await repo.simpan(t);if(mounted)Navigator.pop(context,true);}
 @override Widget build(BuildContext c)=>Scaffold(backgroundColor:const Color(0xFFF1F5F9),appBar:AppBar(backgroundColor:blue,foregroundColor:Colors.white,title:const Text('Tambah Temuan',style:TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.all(18),children:[_info('Kode WO',widget.wo.kodeWo),_info('Kode Temuan',kode.isEmpty?'Menyiapkan...':kode),_info('Penyulang',widget.wo.penyulang),_info('Section',widget.wo.section),_field(segmen,'Segmen *'),const SizedBox(height:12),if(object.isEmpty)_drop('Jenis Object *',['Jaringan','Gardu'],object,(v)=>setState(()=>object=v!))else _info('Jenis Object',object),_drop('Tier *',['Tier 1','Tier 2'],tier,(v)=>setState((){tier=v!;temuan='';})),_drop('Temuan *',temuanOptions,temuan,(v)=>setState(()=>temuan=v!)),if(object=='Jaringan')_field(jarak,'Jarak Terhadap Jaringan (m) *',number:true),if(vegetasi)...[_drop('Jenis Pohon *',pohonMaster.map((r)=>_pick(r,['Jenis Pohon','Pohon','Nama'])).where((x)=>x.isNotEmpty).toSet().toList(),pohon,(v)=>setState(()=>pohon=v!)),_field(tinggi,'Tinggi Pohon (m) *',number:true)],const SizedBox(height:12),OutlinedButton.icon(onPressed:_gps,icon:const Icon(Icons.my_location),label:Text(gps==null?'Ambil Koordinat Temuan':'Akurasi ${gps!.accuracyLabel}')),const SizedBox(height:8),OutlinedButton.icon(onPressed:()async{final v=await _camera('Foto Temuan');if(mounted)setState(()=>foto=v);},icon:const Icon(Icons.camera_alt),label:Text(foto.isEmpty?'Ambil Foto Temuan':'Foto Temuan siap')),const SizedBox(height:8),OutlinedButton.icon(onPressed:()async{final v=await _camera('Foto Lingkungan');if(mounted)setState(()=>lingkungan=v);},icon:const Icon(Icons.camera_alt),label:Text(lingkungan.isEmpty?'Ambil Foto Lingkungan':'Foto Lingkungan siap')),const SizedBox(height:20),ElevatedButton(onPressed:saving?null:_save,style:ElevatedButton.styleFrom(backgroundColor:amber,foregroundColor:navy,minimumSize:const Size.fromHeight(52)),child:Text(saving?'Menyimpan...':'Simpan Temuan',style:const TextStyle(fontWeight:FontWeight.w800)))]));
 Widget _info(String a,String b)=>Padding(padding:const EdgeInsets.only(bottom:12),child:InputDecorator(decoration:InputDecoration(labelText:a,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:line))),child:Text(b.isEmpty?'-':b,style:const TextStyle(fontWeight:FontWeight.w700))));
 Widget _field(TextEditingController c,String l,{bool number=false})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:c,keyboardType:number?const TextInputType.numberWithOptions(decimal:true):TextInputType.text,decoration:InputDecoration(labelText:l,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))));
 Widget _drop(String l,List<String>o,String v,ValueChanged<String?>f)=>Padding(padding:const EdgeInsets.only(bottom:12),child:DropdownButtonFormField<String>(initialValue:o.contains(v)?v:null,items:o.map((x)=>DropdownMenuItem(value:x,child:Text(x,overflow:TextOverflow.ellipsis))).toList(),onChanged:f,isExpanded:true,decoration:InputDecoration(labelText:l,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))));
}