-- Referensi skema WO Har Jar (dieksekusi via database_helper.dart / sqlite_service v6)

CREATE TABLE wo_har_jar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  no TEXT NOT NULL DEFAULT '',
  kode_wo TEXT NOT NULL UNIQUE,
  kode_uiw TEXT NOT NULL DEFAULT '',
  kode_up3 TEXT NOT NULL DEFAULT '',
  kode_ulp TEXT NOT NULL DEFAULT '',
  ulp TEXT NOT NULL DEFAULT '',
  hari TEXT NOT NULL DEFAULT '',
  tanggal TEXT NOT NULL DEFAULT '',
  penyulang TEXT NOT NULL DEFAULT '',
  section TEXT NOT NULL DEFAULT '',
  segmen TEXT NOT NULL DEFAULT '',
  kode_temuan TEXT NOT NULL DEFAULT '',
  kode_wo_inspeksi TEXT NOT NULL DEFAULT '',
  jenis_object TEXT NOT NULL DEFAULT '',
  tier TEXT NOT NULL DEFAULT '',
  temuan TEXT NOT NULL DEFAULT '',
  prioritas TEXT NOT NULL DEFAULT '',
  pekerjaan TEXT NOT NULL DEFAULT '',
  jenis_wo TEXT NOT NULL DEFAULT '',
  koordinat TEXT NOT NULL DEFAULT '',
  lat REAL,
  long REAL,
  foto_temuan TEXT NOT NULL DEFAULT '',
  link_foto_temuan TEXT NOT NULL DEFAULT '',
  foto_tiang_sekitar TEXT NOT NULL DEFAULT '',
  link_foto_tiang_sekitar TEXT NOT NULL DEFAULT '',
  foto_sesudah TEXT NOT NULL DEFAULT '',
  link_foto_sesudah TEXT NOT NULL DEFAULT '',
  catatan_petugas TEXT NOT NULL DEFAULT '',
  tim_eksekusi TEXT NOT NULL DEFAULT '',
  tanggal_penugasan TEXT NOT NULL DEFAULT '',
  catatan_koordinator TEXT NOT NULL DEFAULT '',
  nama_koordinator TEXT NOT NULL DEFAULT '',
  status_wo TEXT NOT NULL DEFAULT 'Menunggu',
  user_input TEXT NOT NULL DEFAULT '',
  waktu_input TEXT NOT NULL DEFAULT '',
  waktu_realisasi TEXT NOT NULL DEFAULT '',
  folder_path TEXT NOT NULL DEFAULT '',
  is_synced INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE wo_material_har_jar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kode_penggunaan_material TEXT NOT NULL UNIQUE,
  kode_wo TEXT NOT NULL,
  material TEXT NOT NULL DEFAULT '',
  jumlah REAL NOT NULL DEFAULT 0,
  satuan TEXT NOT NULL DEFAULT '',
  kepemilikan TEXT NOT NULL DEFAULT '',
  keterangan TEXT NOT NULL DEFAULT '',
  user_input TEXT NOT NULL DEFAULT '',
  waktu_input TEXT NOT NULL DEFAULT '',
  is_synced INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (kode_wo) REFERENCES wo_har_jar (kode_wo) ON DELETE CASCADE
);
